// List of essays

export const essays = [
    { title: "Founder Mode", url: "https://www.paulgraham.com/foundermode.html" },
    { title: "The Right Kind of Stubborn", url: "https://www.paulgraham.com/persistence.html" },
    { title: "The Reddits", url: "https://www.paulgraham.com/reddits.html" },
    { title: "How To Start Google", url: "https://www.paulgraham.com/google.html"},
    { title: "The Best Essay", url: "https://www.paulgraham.com/best.html"},
    { title: "Superlinear Returns", url: "https://www.paulgraham.com/superlinear.html"},
    { title: "How To Do Great Work", url: "https://www.paulgraham.com/greatwork.html"},
    { title: "How To Get New Ideas", url: "https://www.paulgraham.com/getideas.html"},
    { title: "The Need To Read", url: "https://www.paulgraham.com/read.html"},
    { title: "What You (Want To)* Want", url: "https://www.paulgraham.com/want.html"},
    { title: "Alien Truth", url: "https://www.paulgraham.com/alien.html"},
    { title: "What I've Learned From Users", url: "https://www.paulgraham.com/users.html"},
    { title: "Heresy", url: "https://www.paulgraham.com/heresy.html"},
    { title: "Putting Ideas Into Words", url: "https://www.paulgraham.com/words.html"},
    { title: "Is There Such A Thing As Good Taste?", url: "https://www.paulgraham.com/goodtaste.html"},
    { title: "Beyond Smart", url: "https://www.paulgraham.com/smart.html"},
    { title: "Weird Languages", url: "https://www.paulgraham.com/weird.html"},
    { title: "How To Work Hard", url: "https://www.paulgraham.com/hwh.html"},
    { title: "A Project Of One's Own", url: "https://www.paulgraham.com/own.html"},
    { title: "Fierce Nerds", url: "https://www.paulgraham.com/fn.html"},
    { title: "Crazy New Ideas", url: "https://www.paulgraham.com/newideas.html"},
    { title: "An NFT That Saves Lives", url: "https://www.paulgraham.com/nft.html"},
    { title: "The Real Reason To End The Death Penalty", url: "https://www.paulgraham.com/real.html"},
    { title: "How People Get Rich Now", url: "https://www.paulgraham.com/richnow.html"},
    { title: "Write Simply", url: "https://www.paulgraham.com/simply.html"},
    { title: "Donated Unrestricted", url: "https://www.paulgraham.com/donate.html"},
    { title: "What I Worked On", url: "https://www.paulgraham.com/worked.html"},
    { title: "Earnestness", url: "https://www.paulgraham.com/earnest.html"},
    { title: "Billionaires Build", url: "https://www.paulgraham.com/ace.html"},
    { title: "The Airbnbs", url: "https://www.paulgraham.com/airbnbs.html"},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
    { title: "", url: ""},
]

export default essays;