// List of essays

export const essays = [
    { title: "Founder Mode", url: "https://www.paulgraham.com/foundermode.html" },
    { title: "The Right Kind of Stubborn", url: "https://www.paulgraham.com/persistence.html" },
    { title: "The Reddits", url: "https://www.paulgraham.com/reddits.html" },
    { title: "How To Start Google", url: "https://www.paulgraham.com/google.html"},
    { title: "The Best Essay", url: "https://www.paulgraham.com/best.html"},
    { title: "Superlinear Returns", url: "https://www.paulgraham.com/superlinear.html"},
    { title: "How To Do Great Work", url: "https://www.paulgraham.com/greatwork.html"},
    { title: "How To Get New Ideas", url: "https://www.paulgraham.com/getideas.html"},
    { title: "The Need To Read", url: "https://www.paulgraham.com/read.html"},
    { title: "What You (Want To)* Want", url: "https://www.paulgraham.com/want.html"},
    { title: "Alien Truth", url: "https://www.paulgraham.com/alien.html"},
    { title: "What I've Learned From Users", url: "https://www.paulgraham.com/users.html"},
    { title: "Heresy", url: "https://www.paulgraham.com/heresy.html"},
    { title: "Putting Ideas Into Words", url: "https://www.paulgraham.com/words.html"},
    { title: "Is There Such A Thing As Good Taste?", url: "https://www.paulgraham.com/goodtaste.html"},
    { title: "Beyond Smart", url: "https://www.paulgraham.com/smart.html"},
    { title: "Weird Languages", url: "https://www.paulgraham.com/weird.html"},
    { title: "How To Work Hard", url: "https://www.paulgraham.com/hwh.html"},
    { title: "A Project Of One's Own", url: "https://www.paulgraham.com/own.html"},
    { title: "Fierce Nerds", url: "https://www.paulgraham.com/fn.html"},
    { title: "Crazy New Ideas", url: "https://www.paulgraham.com/newideas.html"},
    { title: "An NFT That Saves Lives", url: "https://www.paulgraham.com/nft.html"},
    { title: "The Real Reason To End The Death Penalty", url: "https://www.paulgraham.com/real.html"},
    { title: "How People Get Rich Now", url: "https://www.paulgraham.com/richnow.html"},
    { title: "Write Simply", url: "https://www.paulgraham.com/simply.html"},
    { title: "Donated Unrestricted", url: "https://www.paulgraham.com/donate.html"},
    { title: "What I Worked On", url: "https://www.paulgraham.com/worked.html"},
    { title: "Earnestness", url: "https://www.paulgraham.com/earnest.html"},
    { title: "Billionaires Build", url: "https://www.paulgraham.com/ace.html"},
    { title: "The Airbnbs", url: "https://www.paulgraham.com/airbnbs.html"},
    { title: "How To Think For Yourself", url: "https://www.paulgraham.com/think.html"},
    { title: "Early Work", url: "https://www.paulgraham.com/early.html"},
    { title: "Modeling A Wealth Tax", url: "https://www.paulgraham.com/wtax.html"},
    { title: "The Four Quadrants Of Conformism", url: "https://www.paulgraham.com/conformism.html"},
    { title: "Orthodox Privilege", url: "https://www.paulgraham.com/orth.html"},
    { title: "Coronavius And Credebility", url: "https://www.paulgraham.com/cred.html"},
    { title: "How To Write Usefully", url: "https://www.paulgraham.com/useful.html"},
    { title: "Being A Noob", url: "https://www.paulgraham.com/noob.html"},
    { title: "Haters", url: "https://www.paulgraham.com/fh.html"},
    { title: "The Two Kinds Of Moderate", url: "https://www.paulgraham.com/mod.html"},
    { title: "Fashionable Problems", url: "https://www.paulgraham.com/fp.html"},
    { title: "Having Kids", url: "https://www.paulgraham.com/kids.html"},
    { title: "The Lesson To Unlearn", url: "https://www.paulgraham.com/lesson.html"},
    { title: "Novelty And Heresy", url: "https://www.paulgraham.com/nov.html"},
    { title: "The Bus Ticket Theory Of Genius", url: "https://www.paulgraham.com/genius.html"},
    { title: "General And Surprising", url: "https://www.paulgraham.com/sun.html"},
    { title: "Charisma / Power", url: "https://www.paulgraham.com/pow.html"},
    { title: "The Risk Of Discovery", url: "https://www.paulgraham.com/disc.html"},
    { title: "How To Make Pittsburgh A Startup Hub", url: "https://www.paulgraham.com/pgh.html"},
    { title: "Life Is Short", url: "https://www.paulgraham.com/vb.html"},
    { title: "Economic Inequality", url: "https://www.paulgraham.com/ineq.html"},
    { title: "The Refragmentation", url: "https://www.paulgraham.com/re.html"},
    { title: "Jessica Livingston", url: "https://www.paulgraham.com/jessica.html"},
    { title: "A Way To Detect Bias", url: "https://www.paulgraham.com/bias.html"},
    { title: "Write Like You Talk", url: "https://www.paulgraham.com/talk.html"},
    { title: "Default Alive Or Default Dead?", url: "https://www.paulgraham.com/aord.html"},
    { title: "Why It's Safe For Founders To Be Nice", url: "https://www.paulgraham.com/safe.html"},
    { title: "Change Your Name", url: "https://www.paulgraham.com/name.html"},
    { title: "What Mircrosoft Is This The Altair Basic Of?", url: "https://www.paulgraham.com/altair.html"},
    { title: "The Ronco Principle", url: "https://www.paulgraham.com/ronco.html"},
    { title: "What Doesn't Seem Like Work?", url: "https://www.paulgraham.com/work.html"},
    { title: "Don't Talk To Corp Dev", url: "https://www.paulgraham.com/corpdev.html"},
    { title: "Let The Other 95% Of Great Programmers In", url: "https://www.paulgraham.com/95.html"},
    { title: "How To Be An Expert In A Changing World", url: "https://www.paulgraham.com/ecw.html"},
    { title: "How You Know", url: "https://www.paulgraham.com/know.html"},
    { title: "The Fatal Pinch", url: "https://www.paulgraham.com/pinch.html"},
    { title: "Mean People Fail", url: "https://www.paulgraham.com/mean.html"},
    { title: "Before The Startup", url: "https://www.paulgraham.com/before.html"},
    { title: "How To Raise Money", url: "https://www.paulgraham.com/fr.html"},
    { title: "Investor Herd Dynamics", url: "https://www.paulgraham.com/herd.html"},
    { title: "How To Convince Investors", url: "https://www.paulgraham.com/convince.html"},
    { title: "Do Things That Don't Scale", url: "https://www.paulgraham.com/ds.html"},
    { title: "Startup Investing Trends", url: "https://www.paulgraham.com/invtrend.html"},
    { title: "How To Get Startup Ideas", url: "https://www.paulgraham.com/startupideas.html"},
    { title: "The Hardware Renaissance", url: "https://www.paulgraham.com/hw.html"},
    { title: "Startup = Growth", url: "https://www.paulgraham.com/growth.html"},
    { title: "Black Swan Farming", url: "https://www.paulgraham.com/swan.html"},
    { title: "The Top Of My ToDo List", url: "https://www.paulgraham.com/todo.html"},
    { title: "Writing And Speaking", url: "https://www.paulgraham.com/speak.html"},
    { title: "How Y Combinator Started", url: "https://www.paulgraham.com/ycstart.html"},
    { title: "Defining Property", url: "https://www.paulgraham.com/property.html"},
    { title: "Frighteningly Ambitious Startup Ideas", url: "https://www.paulgraham.com/ambitious.html"},
    { title: "A Word to the Resourceful", url: "https://www.paulgraham.com/word.html"},
    { title: "Schlep Blindness", url: "https://www.paulgraham.com/schlep.html"},
    { title: "Snapshot: Viaweb, June 1998", url: "https://www.paulgraham.com/vw.html"},
    { title: "With Startup Hubs Work", url: "https://www.paulgraham.com/hubs.html"},
    { title: "The Patent Pledge", url: "https://www.paulgraham.com/patentpledge.html"},
    { title: "Subject: Airbnb", url: "https://www.paulgraham.com/airbnb.html"},
    { title: "Founder Control", url: "https://www.paulgraham.com/control.html"},
    { title: "Tablets", url: "https://www.paulgraham.com/tablets.html"},
    { title: "What We Look For In Founders", url: "https://www.paulgraham.com/founders.html"},
    { title: "The New Funding Landscape", url: "https://www.paulgraham.com/superangels.html"},
    { title: "Where To See Silicon Valley", url: "https://www.paulgraham.com/seesv.html"},
    { title: "High Resolution Fundraising", url: "https://www.paulgraham.com/hiresfund.html"},
    { title: "What Happened To Yahoo", url: "https://www.paulgraham.com/yahoo.html"},
    { title: "The Future Of Startup Funding", url: "https://www.paulgraham.com/future.html"},
    { title: "The Acceleration Of Addictiveness", url: "https://www.paulgraham.com/addiction.html"},
    { title: "The Top Idea In Your Mind", url: "https://www.paulgraham.com/top.html"},
    { title: "How To Lose Time And Money", url: "https://www.paulgraham.com/selfindulgence.html"},
    { title: "Organic Statup Ideas", url: "https://www.paulgraham.com/organic.html"},
    { title: "Apple's Mistake", url: "https://www.paulgraham.com/apple.html"},
    { title: "What Startups Are Really Like", url: "https://www.paulgraham.com/really.html"},
    { title: "Persuade xor Discover", url: "https://www.paulgraham.com/discover.html"},
    { title: "Post-Medium Publishing", url: "https://www.paulgraham.com/publishing.html"},
    { title: "The List Of N Things", url: "https://www.paulgraham.com/nthings.html"},
    { title: "The Anatomy Of Determination", url: "https://www.paulgraham.com/determination.html"},
    { title: "What Kate Saw In Silicon Valley", url: "https://www.paulgraham.com/kate.html"},
    { title: "The Trouble With The Segway", url: "https://www.paulgraham.com/segway.html"},
    { title: "Ramen Profitable", url: "https://www.paulgraham.com/ramenprofitable.html"},
    { title: "Maker's Schedule, Manager's Schedule ", url: "https://www.paulgraham.com/makersschedule.html"},
    { title: "A Local Revolution?", url: "https://www.paulgraham.com/revolution.html"},
    { title: "Why Twitter is a Big Deal", url: "https://www.paulgraham.com/twitter.html"},
    { title: "The Founder Visa", url: "https://www.paulgraham.com/foundervisa.html"},
    { title: "Five Founders", url: "https://www.paulgraham.com/5founders.html"},
    { title: "Relentlessly Resourceful", url: "https://www.paulgraham.com/relres.html"},
    { title: "How To Be An Angel Investor", url: "https://www.paulgraham.com/angelinvesting.html"},
    { title: "Why TV Lost", url: "https://www.paulgraham.com/convergence.html"},
    { title: "Can You Buy a Silicon Valley?  Maybe.", url: "https://www.paulgraham.com/maybe.html"},
    { title: "What I've Learned from Hacker News", url: "https://www.paulgraham.com/hackernews.html"},
    { title: "Startup In 13 Sentences", url: "https://www.paulgraham.com/13sentences.html"},
    { title: "Keep Your Identity Small", url: "https://www.paulgraham.com/identity.html"},
    { title: "After Credentials", url: "https://www.paulgraham.com/credentials.html"},
    { title: "Could VC Be A Casualty Of The Recession?", url: "https://www.paulgraham.com/divergence.html"},
    { title: "The High-Res Society", url: "https://www.paulgraham.com/highres.html"},
    { title: "The Other Half Of 'Artists Ship", url: "https://www.paulgraham.com/artistsship.html"},
    { title: "Why To Start A Startup In A Bad Economy", url: "https://www.paulgraham.com/badeconomy.html"},
    { title: "A Fundraising Survival Guide", url: "https://www.paulgraham.com/fundraising.html"},
    { title: "The Pooled-Risk Company Management Company", url: "https://www.paulgraham.com/prcmc.html"},
    { title: "Cities And Ambition", url: "https://www.paulgraham.com/cities.html"},
    { title: "Disconnecting Distraction", url: "https://www.paulgraham.com/distraction.html"},
    { title: "Lies We Tell Kids", url: "https://www.paulgraham.com/lies.html"},
    { title: "Be Good", url: "https://www.paulgraham.com/good.html"},
    { title: "Why There Aren't More Googles", url: "https://www.paulgraham.com/googles.html"},
    { title: "Some Heroes", url: "https://www.paulgraham.com/heroes.html"},
    { title: "How To Disagree", url: "https://www.paulgraham.com/disagree.html"},
    { title: "You Weren't Meant To Have A Boss", url: "https://www.paulgraham.com/boss.html"},
    { title: "A New Venture Animal", url: "https://www.paulgraham.com/ycombinator.html"},
    { title: "Trolls", url: "https://www.paulgraham.com/trolls.html"},
    { title: "Six Principles For Making New Things", url: "https://www.paulgraham.com/newthings.html"},
    { title: "Why To Move To A Startup Hub", url: "https://www.paulgraham.com/startuphubs.html"},
    { title: "The Future Of Web Startups", url: "https://www.paulgraham.com/webstartups.html"},
    { title: "How To Do Philosophy", url: "https://www.paulgraham.com/philosophy.html"},
    { title: "News From The Front", url: "https://www.paulgraham.com/colleges.html"},
    { title: "How Not To Die", url: "https://www.paulgraham.com/die.html"},
    { title: "Holding A Program In One's Head", url: "https://www.paulgraham.com/head.html"},
    { title: "Stuff", url: "https://www.paulgraham.com/stuff.html"},
    { title: "The Equity Equation", url: "https://www.paulgraham.com/equity.html"},
    { title: "An Alternative Theory Of Unions", url: "https://www.paulgraham.com/unions.html"},
    { title: "The Hacker's Guide To Investors", url: "https://www.paulgraham.com/guidetoinvestors.html"},
    { title: "Two Kinds Of Judgement", url: "https://www.paulgraham.com/judgement.html"},
    { title: "Microsoft Is Dead", url: "https://www.paulgraham.com/microsoft.html"},
    { title: "Why To Not Not Start A Startup", url: "https://www.paulgraham.com/notnot.html"},
    { title: "Is It Worth Being Wise?", url: "https://www.paulgraham.com/wisdom.html"},
    { title: "Learning From Founders", url: "https://www.paulgraham.com/foundersatwork.html"},
    { title: "How Art Can Be Good", url: "https://www.paulgraham.com/goodart.html"},
    { title: "The 18 Mistakes That Kill Startups", url: "https://www.paulgraham.com/startupmistakes.html"},
    { title: "A Student's Guide To Startups", url: "https://www.paulgraham.com/mit.html"},
    { title: "How To Present To Investors", url: "https://www.paulgraham.com/investors.html"},
    { title: "Copy What You Like", url: "https://www.paulgraham.com/copy.html"},
    { title: "The Island Test", url: "https://www.paulgraham.com/island.html"},
    { title: "The Power Of The Marginal", url: "https://www.paulgraham.com/marginal.html"},
    { title: "Why Startups Condense In America", url: "https://www.paulgraham.com/america.html"},
    { title: "How To Be Silicon Valley", url: "https://www.paulgraham.com/siliconvalley.html"},
    { title: "The Hardest Lessons For Startups To Learn", url: "https://www.paulgraham.com/startuplessons.html"},
    { title: "See Randomness", url: "https://www.paulgraham.com/randomness.html"},
    { title: "Are Software Patents Evil?", url: "https://www.paulgraham.com/softwarepatents.html"},
    { title: "6,631,372", url: "https://www.paulgraham.com/6631327.html"},
    { title: "Why YC", url: "https://www.paulgraham.com/whyyc.html"},
    { title: "How To Do What You Like", url: "https://www.paulgraham.com/love.html"},
    { title: "Good And Bad Procrastination", url: "https://www.paulgraham.com/procrastination.html"},
    { title: "Web 2.0", url: "https://www.paulgraham.com/web20.html"},
    { title: "How To Fund A Startup", url: "https://www.paulgraham.com/startupfunding.html"},
    { title: "The Ventrure Capital Squeeze", url: "https://www.paulgraham.com/vcsqueeze.html"},
    { title: "Ideas For Startups", url: "https://www.paulgraham.com/ideas.html"},
    { title: "What I Did This Summer", url: "https://www.paulgraham.com/sfp.html"},
    { title: "Inequality And Risk", url: "https://www.paulgraham.com/inequality.html"},
    { title: "After The Ladder", url: "https://www.paulgraham.com/ladder.html"},
    { title: "What Business Can Learn From Open Source", url: "https://www.paulgraham.com/opensource.html"},
    { title: "Hiring Is Obsolete", url: "https://www.paulgraham.com/hiring.html"},
    { title: "The Submarine", url: "https://www.paulgraham.com/submarine.html"},
    { title: "Why Smart People Have Bad Ideas", url: "https://www.paulgraham.com/bronze.html"},
    { title: "Return Of The Mac", url: "https://www.paulgraham.com/mac.html"},
    { title: "Writing, Briefly", url: "https://www.paulgraham.com/writing44.html"},
    { title: "Undergraduation", url: "https://www.paulgraham.com/college.html"},
    { title: "A Unified Theory Of VC Suckage", url: "https://www.paulgraham.com/venturecapital.html"},
    { title: "What You'll Whish You'd Known", url: "https://www.paulgraham.com/hs.html"},
    { title: "Made In USA", url: "https://www.paulgraham.com/usa.html"},
    { title: "It's Charisma, Stupid", url: "https://www.paulgraham.com/charisma.html"},
    { title: "Bradley's Ghost", url: "https://www.paulgraham.com/polls.html"},
    { title: "A Version 1.0", url: "https://www.paulgraham.com/laundry.html"},
    { title: "What The Bubble Got Right", url: "https://www.paulgraham.com/bubble.html"},
    { title: "The Age Of The Essay", url: "https://www.paulgraham.com/essay.html"},
    { title: "The Python Paradox", url: "https://www.paulgraham.com/pypar.html"},
    { title: "Great Hackers", url: "https://www.paulgraham.com/gh.html"},
    { title: "Mind The Gap", url: "https://www.paulgraham.com/gap.html"},
    { title: "How To Make Wealth", url: "https://www.paulgraham.com/wealth.html"},
    { title: "The Word 'Hacker", url: "https://www.paulgraham.com/gba.html"},
    { title: "What You Can't Say", url: "https://www.paulgraham.com/say.html"},
    { title: "Filters That Fight Back", url: "https://www.paulgraham.com/ffb.html"},
    { title: "Hackers And Painters", url: "https://www.paulgraham.com/hp.html"},
    { title: "If Lisp Is So Great", url: "https://www.paulgraham.com/iflisp.html"},
    { title: "The Hundred-Year Language", url: "https://www.paulgraham.com/hundred.html"},
    { title: "Why Nerds Are Unpopular", url: "https://www.paulgraham.com/nerds.html"},
    { title: "Better Bayesian Filtering", url: "https://www.paulgraham.com/better.html"},
    { title: "Design And Research", url: "https://www.paulgraham.com/desres.html"},
    { title: "Revenge Of The Nerds", url: "https://www.paulgraham.com/icad.html"},
    { title: "Succinctness Is Power", url: "https://www.paulgraham.com/power.html"},
    { title: "What Languages Fix", url: "https://www.paulgraham.com/fix.html"},
    { title: "Taste For Makers", url: "https://www.paulgraham.com/taste.html"},
    { title: "Why Arc Isn't Especially Object-Oriented", url: "https://www.paulgraham.com/noop.html"},
    { title: "What Made Lisp Different", url: "https://www.paulgraham.com/diff.html"},
    { title: "The Other Road Ahead", url: "https://www.paulgraham.com/road.html"},
    { title: "The Roots Of Lisp", url: "https://www.paulgraham.com/rootsoflisp.html"},
    { title: "Five Questions About Language Design", url: "https://www.paulgraham.com/langdes.html"},
    { title: "Being Popular", url: "https://www.paulgraham.com/popular.html"},
    { title: "Java's Cover", url: "https://www.paulgraham.com/javacover.html"},
    { title: "Beating The Averages", url: "https://www.paulgraham.com/avg.html"},
    { title: "Lisp For Web-Based Applications", url: "https://www.paulgraham.com/lwba.html"},
    { title: "Chapter 1 of Ansi Common Lisp", url: "https://sep.turbifycdn.com/ty/cdn/paulgraham/acl1.txt?t=1725212754&"},
    { title: "Chapter 2 of Ansi Common Lisp", url: "https://sep.turbifycdn.com/ty/cdn/paulgraham/acl2.txt?t=1725212754&"},
    { title: "Programming Bottom-Up", url: "https://www.paulgraham.com/progbot.html"},
    { title: "This Year We Can End The Death Penalty In California", url: "https://www.paulgraham.com/prop62.html"},
]

export default essays;
